### ISSUE TITLE
The Visualization tools

### ISSUE THREAD

**Issue by Orbis36** [stevewongv/Sparse2Dense#1]
Hi there,

Thanks a lot for your great work first.
Personally, I really love your visualization format, could you tell me the package or software you are using?
It seems not simply plotted by Open3D.
I'll very much appreciate it if you can provide some codes for visualization.

**Comment by stevewongv** [comment]
Hi,

Thanks for your kind words. 

It is simple to visualize the features by using seaborn. You can take each channel as a figure. You need to normalize the feature and then use seaborn to draw the heatmap.

**Comment by Orbis36** [comment]
Oh, thanks for your reply.
However， what I mean is the visualization of cloud points, like the gif in your readme file and Figure 3 (in paper).

**Comment by stevewongv** [comment]
These are generated by using blender.

**Comment by Orbis36** [comment]
Thank you so much
