### ISSUE TITLE
the training codes of Sparse2Dense

### ISSUE THREAD

**Issue by WWW2323** [stevewongv/Sparse2Dense#3]
Dear author, did you provide the distillation codes of sparse2dense in this codebase?  And the sparse2dense config seems empty such as [SECOND+S2D](https://github.com/stevewongv/Sparse2Dense/blob/main/configs/waymo/voxelnet/waymo_centerpoint_second_3x_distill_interval_5.py), [CenterPoint-Pillar+S2D](https://github.com/stevewongv/Sparse2Dense/blob/main/configs/waymo/pp/two_stage/waymo_centerpoint_pp_two_pfn_stride1_two_stage_bev_distill_interval_5) and [CenterPoint+S2D](https://github.com/stevewongv/Sparse2Dense/blob/main/configs/waymo/voxelnet/two_stage/waymo_centerpoint_voxelnet_two_stage_distill_interval_5.py).

**Comment by stevewongv** [comment]
Thanks for your report! Some errors occurred in GitHub uploading progress. I have manually uploaded the configs and fixed the links. Please tell me if any issues occur!
