### ISSUE TITLE
Some questions about the code and data

### ISSUE THREAD

**Issue by QingXIA233** [stevewongv/Sparse2Dense#4]
Hello, I've read your paper and really get caught by your impressive work. I'm currently trying to train CenterPoint-PointPillar model with your provided method. But I encountered some problems when I try to use the code and data in this repo:
1. Some modules and scripts seem to be missing, maybe it's uploading-related issue?
I know some modules can be got from CenterPoint Repo, however, I couldn't find this one below in CenterPoint repo nor this repo. Could you provide this module please? This will help a lot. 
<img width="671" alt="issue1" src="https://user-images.githubusercontent.com/64100948/215313926-1b461255-69b8-467f-a9fb-052067550e24.png">

2. I emailed to you before and got your generated Dense Object dataset, which is a folder containing a large number of pkl files. I wonder whether they should be matched with the content of /lidar and /annos under the /train folder. Because I split WOD to train and val randomly by 4:1, maybe not the same with your split way. I'm afraid this may be a problem. In short, my question is: should **/gt** be matched with **/annos** and **/lidar**? If so, could you provide me the split txt files of train and val data of your own. (I have downloaded the WOD dataset, so only the file names in different splits are needed).

Waiting for your reply, thanks in advance.

**Comment by stevewongv** [comment]
Thanks for your report. I just added the missing files. You can try it now. 

For the second question, the dense object set is generated for the training set, and the name of the files is the id name provided by Waymo. We use this id name to replace the original object with the dense object. Thus, you'll need to re-prepare the database-related files following our instructions: 
```
python tools/create_data.py waymo_data_prep --root_path=data/waymo --split train --nsweeps=1

python tools/create_data.py waymo_data_prep --root_path=data/waymo --split val --nsweeps=1
```
to add the id name into the pkl https://github.com/stevewongv/Sparse2Dense/blob/183fe5248cd014bc3761fd57c8aff3f34eda80aa/det3d/datasets/waymo/waymo_common.py#L283.

**Comment by stevewongv** [comment]
Send me the email again, I can share the val set version of the dense object.

**Comment by QingXIA233** [comment]
Thank you a lot. My model is training now. Close this issue.
